### PR TITLE
Add Job XP gain

### PR DESCRIPTION
**Pull request by ravak**

### CODE REVIEW

**Comment by fiote** [comment]
Hi @ravak, I did some changes on the cwfarmed. Do you mind updating your pull? It's not much to do :)

**Comment by ravak** [comment]
Will do. Please have a look at my master branch, as I've added some more
functionality (silver changes from before, and elapsed time between
updates). You can cherry-pick commits or I can make a PR with all those
changes.

**Comment by fiote** [comment]
Do you mind sending here an SS of how the elapsed-time appears on the chat?

**Comment by ravak** [comment]
In 6 hours, office time right now. It's something like:

[BaseXP] +1% (3242 pts/3 mobs) in 00:12:02.
[JobXP] +1% (6342 pts/12 mobs) in 00:01:02.
[Silver] +1034 (23 mobs) in 00:42:02.

This is with threshold of 1% for xp and 1000 silver. If there is no silver,
it will skip mob count. Time format is hours:minutes:seconds.

**Comment by fiote** [comment]
I just checked your repo and you're not counting mobs on silver (and that's correct). I really like your timing thing, gonna merge it as soon as you update/PR it again (in ~6 hours ^^)

**Comment by LeoLombardi** [comment]
Fiote, sorry for intruding on this commit comment log - I'm working on a companion app for TOS (https://github.com/LeoLombardi/tos-laimas-compass), and I'd like to know if I can embed your dynamic loader as part of the Win32 installer.

Excluron pointed out to me that the loader I wrote is actually quite similar to yours (https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/pull/122), but I think yours is more fleshed out.

Here's my email in case you would like to continue this talk outside GH: leonardobotinelly at gmail.com .

Oh, and I speak Portuguese as well. =)

**Comment by fiote** [comment]
Keeping in english so anyone can understand: sure, you can use it :)

**Comment by LeoLombardi** [comment]
Oh, the remark was about the personal email. But thanks for your permission!

**Pull request closed without merging**
