### PR TITLE
Elapsed time + jobxp + fiote backmerged

### PR DESCRIPTION
**Pull request by ravak**
Sadly I cannot test your latest master as I don't have a pet (and it doesn't work without a pet).

### CODE REVIEW

**Comment by fiote** [comment]
"and it dont work without a pet" means the entire addon simply doesn't work without pet?

**Comment by ravak** [comment]
Yes, the addon doesn't load, because you try to access a pet that doesn't
exist (resetPet -> getPet).

**Comment by fiote** [comment]
I see! I think I can simply test it with another toon. I'll get your pull and test everything together. Thanks!

**Comment by fiote** [comment]
@ravak I merged, pulled, did some changes and pushed again.

Testing the pet-xp in another toon doesnt help because the game still recognizes as if the toon have it, so I added a ton of checkings to the function with logs too. Can you please run it and see what's the real check to see if there is a pet or not?

**Comment by ravak** [comment]
How about creating a team on another server? Just in case restart the game
client as well? Again - office hours - may test in few hours, assuming I
can log in (due to F2P rush).

**Comment by fiote** [comment]
@ravak AMAZING idea, lol. Just tested and found the correct way to check for the pet. Thanks!

**Pull request merged**
