### PR TITLE
Add mob count to silver gain

### PR DESCRIPTION
**Pull request by ravak**
Implemented similarly to XP gain

### CODE REVIEW

**Comment by fiote** [comment]
I didn't do that on purpose. You know, when you kill more than one monster in a short amount of time, the game will combine the silver and call the event only one time. That means the mob-counter for silver is not really accurate. Thanks for the suggestion, though!

**Comment by ravak** [comment]
I think mob counter for silver is mostly not accurate due to how the hook is working. We bind to a silver drop and not mob kill, thus when mob does not drop any silver it's not counted while it should be counted as +0 silver, but +1 mob.

I'm more interested in some time measure now, like XP+job+silver/minute. Once I have something working I will make a PR.

**Comment by fiote** [comment]
Okay, go for it =)

**Comment by ravak** [comment]
I'm leaving the silver on separate branch for now.

https://github.com/fiote/treeofsavior-addons/compare/master...ravak:silver-per-monster?expand=1

**Pull request closed without merging**
